sonar.organization=chalharu
sonar.projectKey=chalharu_cloudflared-ingress-rs
sonar.projectName=cloudflared-ingress-rs
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=target/**
sonar.rust.lcov.reportPaths=target/llvm-cov/lcov.info
