{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudflared-ingress.serviceAccountName" . }}
  labels:
    {{- include "cloudflared-ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudflared-ingress.clusterRoleName" . }}
  labels:
    {{- include "cloudflared-ingress.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - chalharu.top
    resources:
      - cloudflaredtunnels
      - cloudflaredtunnels/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflared-ingress.clusterRoleBindingName" . }}
  labels:
    {{- include "cloudflared-ingress.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflared-ingress.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflared-ingress.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
